# Generated by Django 3.0.5 on 2020-04-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulate_app', '0003_auto_20200420_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.FileField(upload_to='uploaded_images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.CharField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], max_length=10),
        ),
    ]
