# Generated by Django 3.0.5 on 2020-04-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulate_app', '0005_auto_20200420_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.FloatField(),
        ),
    ]
