# Generated by Django 3.0.5 on 2020-04-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulate_app', '0008_auto_20200422_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embed_link',
            field=models.URLField(blank=True, null=True, verbose_name='Embed Link'),
        ),
        migrations.AddField(
            model_name='article',
            name='link_url',
            field=models.URLField(blank=True, null=True, verbose_name='Normal Link'),
        ),
    ]
