# Generated by Django 3.0.5 on 2020-04-22 12:38

import articulate_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulate_app', '0009_auto_20200422_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creatives',
            field=models.CharField(default='Not Mentioned', max_length=100, verbose_name='Director/Creation/Youtuber'),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('Series', 'SERIES'), ('Short Film', 'SHORT FILM'), ('Youtube', 'YOUTUBE'), ('Movie', 'MOVIE'), ('Documentary', 'DOCUMENTARY'), ('Album', 'ALBUM')], default=0, max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='embed_link',
            field=models.URLField(blank=True, null=True, verbose_name='Trailer Embed Link'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.FileField(help_text='Maximum file size allowed is 80kb', unique=True, upload_to='uploaded_images/', validators=[articulate_app.models.validate_image], verbose_name='Movie Poster'),
        ),
        migrations.AlterField(
            model_name='article',
            name='imdb_rating',
            field=models.FloatField(validators=[articulate_app.models.validate_imdb_rating], verbose_name='IMDB Rating'),
        ),
        migrations.AlterField(
            model_name='article',
            name='link_url',
            field=models.URLField(blank=True, null=True, verbose_name='Trailer Normal Link'),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.FloatField(validators=[articulate_app.models.validate_rating], verbose_name='My Rating'),
        ),
        migrations.AlterField(
            model_name='article',
            name='review',
            field=models.TextField(verbose_name='Review Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
