# Generated by Django 3.0.5 on 2020-04-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulate_app', '0010_auto_20200422_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='link_url',
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('Album', 'ALBUM'), ('Series', 'SERIES'), ('Movie', 'MOVIE'), ('Documentary', 'DOCUMENTARY'), ('Youtube', 'YOUTUBE'), ('Short Film', 'SHORT FILM')], default=0, max_length=50, verbose_name='Type'),
        ),
    ]
