# Generated by Django 3.0.5 on 2020-04-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulate_app', '0011_auto_20200422_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='embed_link',
            field=models.URLField(blank=True, null=True, verbose_name='Trailer Youtube Link'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('series', 'Series'), ('documentary', 'Documentary'), ('short Film', 'Short Film'), ('youtube', 'Youtube'), ('movie', 'Movie'), ('album', 'Album')], default='movie', max_length=50, verbose_name='Type'),
        ),
    ]
