# Generated by Django 3.0.5 on 2020-04-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulate_app', '0012_auto_20200422_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('Series', 'series'), ('Documentary', 'documentary'), ('Short Film', 'short Film'), ('Youtube', 'youtube'), ('Movie', 'movie'), ('Album', 'album')], default='Movie', max_length=50, verbose_name='Type'),
        ),
    ]
