# Generated by Django 3.0.5 on 2020-04-23 04:50

import articulate_app.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulate_app', '0013_auto_20200422_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='embed_link',
            field=models.URLField(blank=True, help_text='Paste only youtube urls', null=True, verbose_name='Trailer Youtube Link'),
        ),
        migrations.AlterField(
            model_name='article',
            name='imdb_rating',
            field=models.FloatField(help_text='Decimal 0.1 to 10.0', validators=[articulate_app.validators.validate_imdb_rating], verbose_name='IMDB Rating'),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.FloatField(help_text='Decimal 0.1 to 5.0', validators=[articulate_app.validators.validate_rating], verbose_name='Your Rating'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Keep 1st letter Capital', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('Series', 'series'), ('Documentary', 'documentary'), ('Short Film', 'short Film'), ('Youtube', 'youtube'), ('Movie', 'movie'), ('Album', 'album')], default='Movie', help_text='default is Movie', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(help_text='Select yourself from dropdown', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
