# Generated by Django 5.2.7 on 2025-10-26 14:17

import articulate_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulate_app", "0016_article_embedding_alter_article_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.FileField(
                help_text="Maximum file size allowed is 300kb",
                null=True,
                upload_to="",
                validators=[articulate_app.validators.validate_image],
                verbose_name="Movie Poster",
            ),
        ),
    ]
